import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import customersRouter from "./customers";
import suppliersRouter from "./suppliers";
import inquiriesRouter from "./inquiries";
import quotationsRouter from "./quotations";
import purchaseOrdersRouter from "./purchase-orders";
import dashboardRouter from "./dashboard";
import priceHistoryRouter from "./price-history";
import accountingRouter from "./accounting";
import supplierRfqsRouter from "./supplier-rfqs";
import supplierCategoriesRouter from "./supplier-categories";
import portalRouter from "./portal";
import deliveryNotesRouter from "./delivery-notes";
import invoicesRouter from "./invoices";
import reportsRouter from "./reports";
import whatsappWebhookRouter from "./whatsapp-webhook";

const router: IRouter = Router();

router.use(whatsappWebhookRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(customersRouter);
router.use(suppliersRouter);
router.use(inquiriesRouter);
router.use(quotationsRouter);
router.use(purchaseOrdersRouter);
router.use(dashboardRouter);
router.use(priceHistoryRouter);
router.use(accountingRouter);
router.use(supplierRfqsRouter);
router.use(supplierCategoriesRouter);
router.use(portalRouter);
router.use(deliveryNotesRouter);
router.use(invoicesRouter);
router.use(reportsRouter);

export default router;
